
---

spring:
  profiles:
    active: local
    group:
        local: local
        dev : dev
        staging : staging
        debug: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"