spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/withpeace?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      idle-timeout: 300
      max-lifetime: 300
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    open-in-view: false
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
  # Security OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "836722341563-tttjmd0bh8hf7ja01bpv73lq62knuqbk.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
client:
  provider:
    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
    google:
      authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
      token-uri: "https://oauth2.googleapis.com/token"
      user-info-uri: "https://www.googleapis.com/userinfo/v2/me"

cloud:
  aws:
    credentials:
      accessKey: 5xr2304ISFsqYXzVJGFl
      secretKey: o9aJsLeo3UUNUeQWE7JmU3izM8I6rqzwOqQZCuK3
    s3:
      bucket: withpeace
      endpoint: https://kr.object.ncloudstorage.com
      static : http://withpeace.s3-website.kr.object.ncloudstorage.com
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt.secret: uefrfjr8ew9jfejwr9ejf8w3h4j98fj8e94fhorg9hn3owth48hqf384ohtgfu34oqh8w9th438r2j3490rfj2
slack.webhook.url: https://hooks.slack.com/services/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

youth-policy.api-key: 8209a6c285cde4d07010e0dd